# Generated by Django 4.2.5 on 2023-10-15 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('derbtable', '0002_formulario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta_texto', models.CharField(max_length=255)),
            ],
        ),
    ]
