# Generated by Django 4.2.5 on 2023-11-11 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('derbtable', '0004_remove_response_date_response_question_condicion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('question_type', models.CharField(max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('condicion', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
